"""Machine profile registry derived from supplied vendor manuals.

Formerly a single 3,475-line ``profiles.py``.  It is now a package split
by vendor, but every public name the old module exported is re-exported
here, so ``from eap_middleware.profiles import X`` keeps working.
"""

from .base import (
    logger,
    TRANSITION_LP_ACTIVATE_1,
    TRANSITION_LP_ACTIVATE_2,
    TRANSITION_LP_DEACTIVATE_1,
    TRANSITION_LP_DEACTIVATE_2,
    TRANSITION_CTRL_JOB_START,
    TRANSITION_CTRL_JOB_END,
    TRANSITION_LP_ACTIVATE_FROM_PAYLOAD,
    TRANSITION_LP_DEACTIVATE_FROM_PAYLOAD,
    MachineProfile,
    profile_with_subscription_file,
    profile_with_ceid_overrides,
    event_mapping,
    alias_table,
    GENERIC_EVENT_ALIASES,
)
from .generic import (
    GENERIC_SVIDS,
)
from .spts import (
    SPTS_SVIDS,
    SPTS_DVS,
    SPTS_CEID_DV_LAYOUT,
    SPTS_CEID_LOAD_PORT,
    SPTS_CEID_STATE_TRANSITIONS,
    SPTS_CHAMBER_EVENT_CEIDS,
    SPTS_CEID_ALIASES,
)
from .davinci import (
    DAVINCI_SVIDS,
    DAVINCI_CEID_DV_LAYOUT,
    DAVINCI_CEID_LOAD_PORT,
    DAVINCI_CEID_STATE_TRANSITIONS,
    DAVINCI_CHAMBER_EVENT_CEIDS,
    DAVINCI_CEID_ALIASES,
    DAVINCI_DVS,
)
from .ptiq import (
    PTIQ_SVIDS,
    PTIQ_DVS,
)
from .registry import (
    ProfileRegistry,
    built_in_profiles,
)
from .nexgen_mg import (
    NEXGEN_MG_SVIDS,
    mg_port_lot_dvs,
    MG_PORT1_LOT_CHEMISTRY,
    mg_pm_identity_dvs,
    NEXGEN_MG_METRIC_DVS,
    NEXGEN_MG_METRIC_REPORTS,
    NEXGEN_MG_METRIC_BANDS,
    NEXGEN_MG_DVS,
    NEXGEN_MG_REPORTS,
    NEXGEN_MG_CEID_DV_LAYOUT,
    NEXGEN_MG_CEID_LOAD_PORT,
    NEXGEN_MG_CEID_CHAMBER,
    NEXGEN_MG_CHAMBER_EVENT_CEIDS,
    NEXGEN_MG_CEID_STATE_TRANSITIONS,
    NEXGEN_MG_CEID_ALIASES,
    MG_BAND_CORE,
    MG_BAND_PM1,
    MG_BAND_PM2,
    MG_BAND_RECIPE,
    MG_BAND_AUX,
    MG_BAND_SLOT_MAP,
    MG_BAND_WAFER_ALIGNMENT,
    MG_BAND_GEM300_PROCESS_JOB,
    MG_BAND_GEM300_CONTROL_JOB,
    MG_BAND_GEM300_LP_STATE,
    MG_BAND_GEM300_CARRIER,
    MG_BAND_GEM300_LP_ACCESS,
    MG_BAND_GEM300_SUBSTRATE,
    MG_GEM300_BANDS,
    mg_band_gem300,
    mg_band_load_port,
    NEXGEN_MG_CEID_BANDS,
    nexgen_mg_event_aliases,
)

__all__ = [
    "DAVINCI_CEID_ALIASES",
    "DAVINCI_CEID_DV_LAYOUT",
    "DAVINCI_CEID_LOAD_PORT",
    "DAVINCI_CEID_STATE_TRANSITIONS",
    "DAVINCI_CHAMBER_EVENT_CEIDS",
    "DAVINCI_DVS",
    "DAVINCI_SVIDS",
    "GENERIC_EVENT_ALIASES",
    "GENERIC_SVIDS",
    "MG_BAND_AUX",
    "MG_BAND_CORE",
    "MG_BAND_GEM300_CARRIER",
    "MG_BAND_GEM300_CONTROL_JOB",
    "MG_BAND_GEM300_LP_ACCESS",
    "MG_BAND_GEM300_LP_STATE",
    "MG_BAND_GEM300_PROCESS_JOB",
    "MG_BAND_GEM300_SUBSTRATE",
    "MG_BAND_PM1",
    "MG_BAND_PM2",
    "MG_BAND_RECIPE",
    "MG_BAND_SLOT_MAP",
    "MG_BAND_WAFER_ALIGNMENT",
    "MG_GEM300_BANDS",
    "MG_PORT1_LOT_CHEMISTRY",
    "MachineProfile",
    "NEXGEN_MG_CEID_ALIASES",
    "NEXGEN_MG_CEID_BANDS",
    "NEXGEN_MG_CEID_CHAMBER",
    "NEXGEN_MG_CEID_DV_LAYOUT",
    "NEXGEN_MG_CEID_LOAD_PORT",
    "NEXGEN_MG_CEID_STATE_TRANSITIONS",
    "NEXGEN_MG_CHAMBER_EVENT_CEIDS",
    "NEXGEN_MG_DVS",
    "NEXGEN_MG_METRIC_BANDS",
    "NEXGEN_MG_METRIC_DVS",
    "NEXGEN_MG_METRIC_REPORTS",
    "NEXGEN_MG_REPORTS",
    "NEXGEN_MG_SVIDS",
    "PTIQ_DVS",
    "PTIQ_SVIDS",
    "ProfileRegistry",
    "SPTS_CEID_ALIASES",
    "SPTS_CEID_DV_LAYOUT",
    "SPTS_CEID_LOAD_PORT",
    "SPTS_CEID_STATE_TRANSITIONS",
    "SPTS_CHAMBER_EVENT_CEIDS",
    "SPTS_DVS",
    "SPTS_SVIDS",
    "TRANSITION_CTRL_JOB_END",
    "TRANSITION_CTRL_JOB_START",
    "TRANSITION_LP_ACTIVATE_1",
    "TRANSITION_LP_ACTIVATE_2",
    "TRANSITION_LP_ACTIVATE_FROM_PAYLOAD",
    "TRANSITION_LP_DEACTIVATE_1",
    "TRANSITION_LP_DEACTIVATE_2",
    "TRANSITION_LP_DEACTIVATE_FROM_PAYLOAD",
    "alias_table",
    "built_in_profiles",
    "event_mapping",
    "logger",
    "mg_band_gem300",
    "mg_band_load_port",
    "mg_pm_identity_dvs",
    "mg_port_lot_dvs",
    "nexgen_mg_event_aliases",
    "profile_with_ceid_overrides",
    "profile_with_subscription_file",
]
