"""Generate the NexGen MG Series EventSubscription.json from the profile.

The profile's per-CEID V[] layout and this file's report VID lists are two
views of one table (`NEXGEN_MG_REPORTS` in eap_middleware/profiles.py), so
positional decoding cannot drift away from what we actually asked the tool to
send. Regenerate after touching that table:

    python -m scripts.gen_mg_subscription

Reports are numbered 1000000000 + CEID to match the RPTID convention the
gateway's S6F11 parser uses to pick the right report out of a multi-report
message (gateway/host.py: _parse_event_data).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from eap_middleware.profiles import (
    NEXGEN_MG_CEID_ALIASES,
    NEXGEN_MG_CEID_BANDS,
    NEXGEN_MG_DVS,
    NEXGEN_MG_REPORTS,
    NEXGEN_MG_SVIDS,
)

# Anchored to the repo, not the caller's working directory.
OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "output" / "nexgen_mg_series" / "EventSubscription.json"
)
RPTID_BASE = 1000000000


def build() -> dict:
    reports = []
    events = []
    for ceid in sorted(NEXGEN_MG_CEID_ALIASES):
        name = NEXGEN_MG_CEID_ALIASES[ceid]
        band = NEXGEN_MG_CEID_BANDS[ceid]
        slots = NEXGEN_MG_REPORTS.get(ceid)
        rptids = []
        if slots:
            rptid = RPTID_BASE + ceid
            reports.append({
                "rptid": rptid,
                "name": f"{name}Report",
                "description": f"Report for collection event {ceid} ({name})",
                "band": band,
                "dvids": [vid for _slot, vid in slots],
                "_slots": [slot for slot, _vid in slots],
            })
            rptids = [rptid]
        events.append({
            "ceid": ceid,
            "name": name,
            "description": f"NexGen MG collection event {ceid}",
            "band": band,
            "rptids": rptids,
            "enabled": True,
        })
    return {
        "description": (
            "NexGen Wafersystems MG Series (MG21/MG22/MG22-300) event "
            "subscription, generated by scripts/gen_mg_subscription.py from "
            "eap_middleware.profiles:NEXGEN_MG_REPORTS. Do not hand-edit. "
            "Each entry carries a 'band': the middleware issues S2F33/S2F35/"
            "S2F37 once per band so a CEID a given MG variant does not "
            "implement degrades one family instead of voiding the whole "
            "subscription. Events with an empty 'rptids' list have no valid "
            "data variables in the manual and are enabled WITHOUT being "
            "linked - sending an empty RPTID list would delete the link."
        ),
        "_source": "NWS MG Series SECS/GEM Documentation V1.1.18 (01.04.2025), sections 8.1 / 8.2",
        "_warning": (
            "Documentation-derived and NOT hardware-verified. The manual "
            "states CEIDs, VIDs and processing-state numbers may change "
            "without prior notice."
        ),
        "reports": reports,
        "events": events,
        # Name every VID any report references, not just the data-variable
        # table. Manual 8.2 lists portIdLastMapped (4305) and mapResultLastMap
        # (4306) among the STATUS variables, yet cassetteMappedReport (CEID 145)
        # uses them, so a DVS-only map leaves them unnamed. That matters:
        # `_overlay_from_subscription` discards a CEID's whole layout when any
        # of its DV names is blank, so CEID 145 would silently lose its layout
        # in any profile that did not already hardcode it.
        "dvid_names": _report_vid_names(reports),
    }


def _report_vid_names(reports: List[Dict[str, Any]]) -> Dict[str, str]:
    """{vid: name} covering the DV table plus any report VID drawn from SVIDs."""
    names = {vid: name for name, vid in NEXGEN_MG_DVS.items()}
    by_svid = {vid: name for name, vid in NEXGEN_MG_SVIDS.items()}
    for report in reports:
        for vid in report.get("dvids", []):
            if int(vid) not in names and int(vid) in by_svid:
                names[int(vid)] = by_svid[int(vid)]
    missing = sorted(
        int(vid)
        for report in reports
        for vid in report.get("dvids", [])
        if int(vid) not in names
    )
    if missing:
        raise SystemExit(
            f"report VIDs absent from both the DV and SVID tables: {missing}"
        )
    return {str(vid): name for vid, name in sorted(names.items())}


def main() -> None:
    data = build()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(
        f"Wrote {OUTPUT}: {len(data['reports'])} reports, "
        f"{len(data['events'])} events, "
        f"{len({e['band'] for e in data['events']})} bands"
    )


if __name__ == "__main__":
    main()
